# Generated by Django 3.1.2 on 2021-02-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210209_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='device_type',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
    ]
