# Generated by Django 3.1.2 on 2021-01-27 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_forgotpassword_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forgotpassword',
            name='email',
        ),
    ]
