# Generated by Django 3.1.2 on 2021-02-09 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userdevice_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
