# Generated by Django 3.1.2 on 2021-01-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_forgotpassword_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgotpassword',
            name='otp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
