# Generated by Django 3.1.2 on 2021-01-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_forgotpassword_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpassword',
            name='otp',
            field=models.IntegerField(null=True),
        ),
    ]
