# Generated by Django 3.1.2 on 2021-01-29 11:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210129_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgotpassword',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
